name: pvr
description: Un juego de preguntas de fútbol en Flutter
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/questions.json
